name: android

on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    env:
      ONNX_VERSION: v1.15.0
      SHARED_PKG_NAME: onnxruntime-1.15.0-android-shared

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 检出onnxruntime
      - name: checkout onnxruntime
        uses: actions/checkout@v3
        with:
          repository: microsoft/onnxruntime
          path: onnxruntime-${{ env.ONNX_VERSION }}
          ref: ${{ env.ONNX_VERSION }}
          submodules: recursive

      # 复制编译脚本
      - name: copy build script
        run: |
          cp build-onnxruntime-android.sh onnxruntime-${{ env.ONNX_VERSION }}
          cp onnxruntime_cmake_options.txt onnxruntime-${{ env.ONNX_VERSION }}

      # 编译
      - name: build
        run: |
          cd onnxruntime-${{ env.ONNX_VERSION }}
          chmod a+x build-onnxruntime-android.sh &&./build-onnxruntime-android.sh

      # install文件夹改名linux，并使用7z压缩
      - name: 7zip
        run: |
          mkdir onnxruntime-shared
          mv onnxruntime-${{ env.ONNX_VERSION }}/Debug_armeabi-v7a_19/Debug/install onnxruntime-shared/armeabi-v7a
          mv onnxruntime-${{ env.ONNX_VERSION }}/Debug_arm64-v8a_21/Debug/install onnxruntime-shared/arm64-v8a
          mv onnxruntime-${{ env.ONNX_VERSION }}/Debug_x86_19/Debug/install onnxruntime-shared/x86
          mv onnxruntime-${{ env.ONNX_VERSION }}/Debug_x86_64_21/Debug/install onnxruntime-shared/x86_64
          mv onnxruntime-${{ env.ONNX_VERSION }}/OnnxRuntimeWrapper.cmake onnxruntime-shared/OnnxRuntimeWrapper.cmake
          7z a ${{ env.SHARED_PKG_NAME }}.7z onnxruntime-shared

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SHARED_PKG_NAME }}
          path: ${{ env.SHARED_PKG_NAME }}.7z