name: OnnxruntimeBuilder

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:

  ubuntu1804:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python-version: [ 3.8.5 ]

    env:
      ONNX_VERSION: v1.15.0
      SHARED_PKG_NAME: onnxruntime-1.15.0-ubuntu1804-shared
      STATIC_PKG_NAME: onnxruntime-1.15.0-ubuntu1804-static

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 配置Python环境 onnxruntime要求python minor version: expecting python 3.6+
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # 检出onnxruntime
      - name: checkout onnxruntime
        uses: actions/checkout@v3
        with:
          repository: microsoft/onnxruntime
          path: onnxruntime-${{ env.ONNX_VERSION }}
          ref: ${{ env.ONNX_VERSION }}
          submodules: recursive

      # 复制编译脚本
      - name: copy build script
        run: |
          cp build-onnxruntime.sh onnxruntime-${{ env.ONNX_VERSION }}
          cp onnxruntime_cmake_options.txt onnxruntime-${{ env.ONNX_VERSION }}

      # 编译
      - name: build
        run: |
          cd onnxruntime-${{ env.ONNX_VERSION }}
          chmod a+x build-onnxruntime.sh &&./build-onnxruntime.sh

      # install文件夹改名linux，并使用7z压缩
      - name: 7zip
        run: |
          mv onnxruntime-${{ env.ONNX_VERSION }}/build/Linux/Debug/install linux
          7z a ${{ env.SHARED_PKG_NAME }}.7z linux
          rm -r -f linux
          mv onnxruntime-${{ env.ONNX_VERSION }}/build/Linux/Debug/install-static linux
          7z a ${{ env.STATIC_PKG_NAME }}.7z linux
          rm -r -f linux

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SHARED_PKG_NAME }}
          path: ${{ env.SHARED_PKG_NAME }}.7z

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.STATIC_PKG_NAME }}
          path: ${{ env.STATIC_PKG_NAME }}.7z

  macos1015:
    runs-on: macos-10.15

    env:
      ONNX_VERSION: v1.15.0
      SHARED_PKG_NAME: onnxruntime-1.15.0-macos1015-shared
      STATIC_PKG_NAME: onnxruntime-1.15.0-macos1015-static

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 检出onnxruntime
      - name: checkout onnxruntime
        uses: actions/checkout@v3
        with:
          repository: microsoft/onnxruntime
          path: onnxruntime-${{ env.ONNX_VERSION }}
          ref: ${{ env.ONNX_VERSION }}
          submodules: recursive

      # 安装openmp
      - name: install openmp
        run: |
          brew install libomp

      # 复制编译脚本
      - name: copy build script
        run: |
          cp build-onnxruntime.sh onnxruntime-${{ env.ONNX_VERSION }}
          cp onnxruntime_cmake_options.txt onnxruntime-${{ env.ONNX_VERSION }}

      # 编译
      - name: build
        run: |
          cd onnxruntime-${{ env.ONNX_VERSION }}
          chmod a+x build-onnxruntime.sh &&./build-onnxruntime.sh

      # install文件夹改名macos，并使用7z压缩
      - name: 7z
        run: |
          mv onnxruntime-${{ env.ONNX_VERSION }}/build/MacOS/Debug/install macos
          7z a ${{ env.SHARED_PKG_NAME }}.7z macos
          rm -r -f macos
          mv onnxruntime-${{ env.ONNX_VERSION }}/build/MacOS/Debug/install-static macos
          7z a ${{ env.STATIC_PKG_NAME }}.7z macos
          rm -r -f macos

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SHARED_PKG_NAME }}
          path: ${{ env.SHARED_PKG_NAME }}.7z

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.STATIC_PKG_NAME }}
          path: ${{ env.STATIC_PKG_NAME }}.7z

  windows-vs2019:
    runs-on: windows-2019

    env:
      ONNX_VERSION: v1.15.0
      SHARED_PKG_NAME: onnxruntime-1.15.0-vs2019-shared
      STATIC_PKG_NAME: onnxruntime-1.15.0-vs2019-static

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 检出onnxruntime
      - name: checkout onnxruntime
        uses: actions/checkout@v3
        with:
          repository: microsoft/onnxruntime
          path: onnxruntime-${{ env.ONNX_VERSION }}
          ref: ${{ env.ONNX_VERSION }}
          submodules: recursive

      # 复制编译脚本
      - name: copy build script
        run: |
          cp build-onnxruntime-vs2019.bat onnxruntime-${{ env.ONNX_VERSION }}
          cp onnxruntime_cmake_options.txt onnxruntime-${{ env.ONNX_VERSION }}

      # 编译
      - name: build
        run: |
          cd onnxruntime-${{ env.ONNX_VERSION }}
          ./build-onnxruntime-vs2019.bat

      # install文件夹改名，并使用7z压缩
      - name: 7zip-md
        run: |
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x64-md/Debug/install windows-x64
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x86-md/Debug/install windows-x86
          7z a ${{ env.SHARED_PKG_NAME }}-md.7z windows-x64 windows-x86
          rm -r -Force windows-x64
          rm -r -Force windows-x86
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x64-md/Debug/install-static windows-x64
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x86-md/Debug/install-static windows-x86
          7z a ${{ env.STATIC_PKG_NAME }}-md.7z windows-x64 windows-x86
          rm -r -Force windows-x64
          rm -r -Force windows-x86

      # 上传artifact
      - name: upload-shared-md
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SHARED_PKG_NAME }}-md
          path: ${{ env.SHARED_PKG_NAME }}-md.7z

      # 上传artifact
      - name: upload-static-md
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.STATIC_PKG_NAME }}-md
          path: ${{ env.STATIC_PKG_NAME }}-md.7z

      # install文件夹改名，并使用7z压缩
      - name: 7zip-mt
        run: |
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x64-mt/Debug/install windows-x64
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x86-mt/Debug/install windows-x86
          7z a ${{ env.SHARED_PKG_NAME }}-mt.7z windows-x64 windows-x86
          rm -r -Force windows-x64
          rm -r -Force windows-x86
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x64-mt/Debug/install-static windows-x64
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x86-mt/Debug/install-static windows-x86
          7z a ${{ env.STATIC_PKG_NAME }}-mt.7z windows-x64 windows-x86
          rm -r -Force windows-x64
          rm -r -Force windows-x86

      # 上传artifact
      - name: upload-shared-mt
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SHARED_PKG_NAME }}-mt
          path: ${{ env.SHARED_PKG_NAME }}-mt.7z

      # 上传artifact
      - name: upload-static-mt
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.STATIC_PKG_NAME }}-mt
          path: ${{ env.STATIC_PKG_NAME }}-mt.7z

  debug:
    needs: [ ubuntu1804, macos1015, windows-vs2019 ]

    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 获取所有的git log和tag
      - name: Unshallow
        run: git fetch --prune --unshallow

      # 获取git log 从 previousTag 到 lastTag
      - name: Get git log
        id: git-log
        run: |
          previousTag=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          lastTag=$(git describe --abbrev=0 --tags)
          echo "previousTag:$previousTag ~ lastTag:$lastTag"
          log=$(git log $previousTag..$lastTag --pretty=format:'- %cd %an: %s\n' --date=format:'%Y-%m-%d %H:%M:%S')
          echo "$log"
          echo "log_state="$log"" >> $GITHUB_ENV

      # 创建Changelog文件 triggered by git tag push
      - name: Generate Changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo -e '${{ env.log_state }}' > Debug.txt

      # 下载artifact
      - name: download
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      # 查看artifact
      - name: list artifact
        run: |
          tree artifacts

      # 创建debug
      - name: create-debug
        id: create-debug
        uses: actions/create-debug@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          debug_name: Debug ${{ github.ref }}
          body_path: Debug.txt
          draft: false
          predebug: false

      - name: upload-ubuntu1804-shared
        uses: actions/upload-debug-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: onnxruntime-1.15.0-ubuntu1804-shared
        with:
          upload_url: ${{ steps.create-debug.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-ubuntu1804-static
        uses: actions/upload-debug-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: onnxruntime-1.15.0-ubuntu1804-static
        with:
          upload_url: ${{ steps.create-debug.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-macos1015-shared
        uses: actions/upload-debug-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: onnxruntime-1.15.0-macos1015-shared
        with:
          upload_url: ${{ steps.create-debug.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-macos1015-static
        uses: actions/upload-debug-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: onnxruntime-1.15.0-macos1015-static
        with:
          upload_url: ${{ steps.create-debug.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-windows-vs2019-shared-md
        uses: actions/upload-debug-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: onnxruntime-1.15.0-vs2019-shared-md
        with:
          upload_url: ${{ steps.create-debug.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-windows-vs2019-static
        uses: actions/upload-debug-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: onnxruntime-1.15.0-vs2019-static-md
        with:
          upload_url: ${{ steps.create-debug.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-windows-vs2019-shared
        uses: actions/upload-debug-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: onnxruntime-1.15.0-vs2019-shared-mt
        with:
          upload_url: ${{ steps.create-debug.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-windows-vs2019-static
        uses: actions/upload-debug-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: onnxruntime-1.15.0-vs2019-static-mt
        with:
          upload_url: ${{ steps.create-debug.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      # 获取指定时区的时间
      # https://github.com/marketplace/actions/get-time-action
      - name: Get Time
        id: time
        uses: JantHsueh/get-time-action@master
        with:
          timeZone: 8

      # 向钉钉发送消息
      # https://github.com/marketplace/actions/web-request-action
      - name: dingtalk
        uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK }}
          method: POST
          payload: '{"msgtype": "text", "text": {"content": "版本更新: ${{ github.repository }}-版本号: ${{ github.ref }} \n 发布时间： ${{ steps.time.outputs.time }} \n 距上个正式版的更新记录: \n${{ env.log_state }}"}}'
          headers: '{"Content-Type": "application/json"}'
