name: windows-vs2019

on:
  workflow_dispatch:

jobs:
  windows-vs2019:
    runs-on: windows-2019

    strategy:
      matrix:
        python-version: [ 3.8.5 ]

    env:
      ONNX_VERSION: v1.15.0
      SHARED_PKG_NAME: onnxruntime-1.15.0-vs2019-shared
      STATIC_PKG_NAME: onnxruntime-1.15.0-vs2019-static

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 检出onnxruntime
      - name: checkout onnxruntime
        uses: actions/checkout@v3
        with:
          repository: microsoft/onnxruntime
          path: onnxruntime-${{ env.ONNX_VERSION }}
          ref: ${{ env.ONNX_VERSION }}
          submodules: recursive

      # 复制编译脚本
      - name: copy build script
        run: |
          cp build-onnxruntime-vs2019.bat onnxruntime-${{ env.ONNX_VERSION }}
          cp onnxruntime_cmake_options.txt onnxruntime-${{ env.ONNX_VERSION }}

      # 编译
      - name: build
        run: |
          cd onnxruntime-${{ env.ONNX_VERSION }}
          ./build-onnxruntime-vs2019.bat

      # install文件夹改名，并使用7z压缩
      - name: 7zip-md
        run: |
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x64-md/Debug/install windows-x64
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x86-md/Debug/install windows-x86
          7z a ${{ env.SHARED_PKG_NAME }}-md.7z windows-x64 windows-x86
          rm -r -Force windows-x64
          rm -r -Force windows-x86
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x64-md/Debug/install-static windows-x64
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x86-md/Debug/install-static windows-x86
          7z a ${{ env.STATIC_PKG_NAME }}-md.7z windows-x64 windows-x86
          rm -r -Force windows-x64
          rm -r -Force windows-x86

      # 上传artifact
      - name: upload-shared-md
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SHARED_PKG_NAME }}-md
          path: ${{ env.SHARED_PKG_NAME }}-md.7z

      # 上传artifact
      - name: upload-static-md
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.STATIC_PKG_NAME }}-md
          path: ${{ env.STATIC_PKG_NAME }}-md.7z

      # install文件夹改名，并使用7z压缩
      - name: 7zip-mt
        run: |
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x64-mt/Debug/install windows-x64
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x86-mt/Debug/install windows-x86
          7z a ${{ env.SHARED_PKG_NAME }}-mt.7z windows-x64 windows-x86
          rm -r -Force windows-x64
          rm -r -Force windows-x86
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x64-mt/Debug/install-static windows-x64
          mv onnxruntime-${{ env.ONNX_VERSION }}/build-x86-mt/Debug/install-static windows-x86
          7z a ${{ env.STATIC_PKG_NAME }}-mt.7z windows-x64 windows-x86
          rm -r -Force windows-x64
          rm -r -Force windows-x86

      # 上传artifact
      - name: upload-shared-mt
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SHARED_PKG_NAME }}-mt
          path: ${{ env.SHARED_PKG_NAME }}-mt.7z

      # 上传artifact
      - name: upload-static-mt
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.STATIC_PKG_NAME }}-mt
          path: ${{ env.STATIC_PKG_NAME }}-mt.7z